export const ERROR_CODES = {
  WHATSAPP_WEBHOOK_INVALID: "WHATSAPP_WEBHOOK_INVALID",
  WHATSAPP_MEDIA_DOWNLOAD_FAILED: "WHATSAPP_MEDIA_DOWNLOAD_FAILED",
  WHATSAPP_SEND_FAILED: "WHATSAPP_SEND_FAILED",
  PAYMENT_CREATION_FAILED: "PAYMENT_CREATION_FAILED",
  PAYMENT_WEBHOOK_INVALID: "PAYMENT_WEBHOOK_INVALID",
  PAYMENT_NOT_CONFIRMED: "PAYMENT_NOT_CONFIRMED",
  IMAGE_GENERATION_FAILED: "IMAGE_GENERATION_FAILED",
  IMAGE_PROVIDER_TIMEOUT: "IMAGE_PROVIDER_TIMEOUT",
  IMAGE_PROVIDER_RATE_LIMITED: "IMAGE_PROVIDER_RATE_LIMITED",
  STORAGE_UPLOAD_FAILED: "STORAGE_UPLOAD_FAILED",
  STORAGE_DELETE_FAILED: "STORAGE_DELETE_FAILED",
  DUPLICATE_WEBHOOK: "DUPLICATE_WEBHOOK",
  DUPLICATE_GENERATION: "DUPLICATE_GENERATION",
  INVALID_ORDER_TRANSITION: "INVALID_ORDER_TRANSITION",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
